services:
  user-db:
    image: postgres:15-alpine
    container_name: user-db
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: ${COMMON_DB_USER}
      POSTGRES_PASSWORD: ${COMMON_DB_PASSWORD}
    volumes:
      - ./infrastructure/postgres/init/user_init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  booking-db:
    image: postgres:15-alpine
    container_name: booking-db
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: ${COMMON_DB_USER}
      POSTGRES_PASSWORD: ${COMMON_DB_PASSWORD}
    volumes:
      - ./infrastructure/postgres/init/booking_init:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432" 

  payment-db:
    image: postgres:15-alpine
    container_name: payment-db
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: ${COMMON_DB_USER}
      POSTGRES_PASSWORD: ${COMMON_DB_PASSWORD}
    volumes:
      - ./infrastructure/postgres/init/payment_init:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432" 

  schedule-db:
    image: postgres:15-alpine
    container_name: schedule-db
    environment:
      POSTGRES_DB: schedule_db
      POSTGRES_USER: ${COMMON_DB_USER}
      POSTGRES_PASSWORD: ${COMMON_DB_PASSWORD}
    volumes:
      - ./infrastructure/postgres/init/schedule_init:/docker-entrypoint-initdb.d
    ports:
      - "5435:5432"

  user-service:
    build: ./user-service
    container_name: user-service
    depends_on:
      - user-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/${USER_DB_NAME:-user_db}
      - SPRING_DATASOURCE_USERNAME=${COMMON_DB_USER:-admin}
      - SPRING_DATASOURCE_PASSWORD=${COMMON_DB_PASSWORD:-secret}
    ports:
      - "8081:8081"


  booking-service:
    build: ./booking-service
    container_name: booking-service
    depends_on:
      - booking-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://booking-db:5432/${BOOKING_DB_NAME:-booking_db}
      - SPRING_DATASOURCE_USERNAME=${COMMON_DB_USER:-admin}
      - SPRING_DATASOURCE_PASSWORD=${COMMON_DB_PASSWORD:-secret}
    ports:
      - "8082:8082"

  payment-service:
    build: ./payment-service
    container_name: payment-service
    depends_on:
      - payment-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://payment-db:5432/${PAYMENT_DB_NAME:-payment_db}
      - SPRING_DATASOURCE_USERNAME=${COMMON_DB_USER:-admin}
      - SPRING_DATASOURCE_PASSWORD=${COMMON_DB_PASSWORD:-secret}
    ports:
      - "8083:8083"

  schedule-service:
    build: ./schedule-service
    container_name: schedule-service
    depends_on:
      - schedule-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://schedule-db:5432/${SCHEDULE_DB_NAME:-schedule_db}
      - SPRING_DATASOURCE_USERNAME=${COMMON_DB_USER:-admin}
      - SPRING_DATASOURCE_PASSWORD=${COMMON_DB_PASSWORD:-secret}
    ports:
      - "8084:8084"

