spring:
  application:
    name: payment-service

  datasource:
    # 'user-db' — это имя из твоего главного docker-compose
    url: jdbc:postgresql://fitness-db:5432/${POSTGRES_DB:payment_db}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:secret}
  jpa:
    hibernate:
      # validate просто проверит, что твои Java-классы соответствуют таблицам в БД.
      # Если написать update или create, Hibernate может изменить твою структуру.
      ddl-auto: validate